Repository essentialkaos/rpmbuilder, pull requests merged in 2018-06, with the labels that each got.

#59 Fix checkPerms function
  SOURCES/rpmunbuilder
Labels: PR • FIX

#60 Version 2.2.1
  SOURCES/rpmbuilder
  SOURCES/rpmunbuilder
  rpmbuilder.spec
Labels: PR • RELEASE

#61 Docker support
  .travis.yml
  LICENSE
  SOURCES/docker-entrypoint
  centos6.docker
  centos7.docker
Labels: PR • NEW FEATURE

#62 Added spec validation to TravisCI config
  .travis.yml
Labels: PR • MAINTENANCE
